=== kalekinata/REST_service_development/src/main/resources/XMLScheme.xsd
<?xml version = "1.0" encoding = "UTF-8"?>
<xs:schema
        xmlns:tns="http://namespaceTest.com/tranQueue"
        targetNamespace="http://namespaceTest.com/tranQueue"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified"
><!--1. Схема должна быть сопоставлено определенное пространство имен, при этом должна быть предусмотрена квалификация элементов, определенных схемой, в документе, построенном на ее основе-->
    <xs:simpleType name="clParam">
        <xs:restriction base="xs:string">
            <xs:enumeration value="inn" />
            <xs:enumeration value="ogrn" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="clReq">
        <xs:restriction base="xs:string"><!--6. Схема должна демонстрировать возможности описания новых простых типов на базе существующих (в том числе описание перечислимого типа) с использованием не менее трех видов фасетов-->
            <xs:enumeration value="kpp" />
            <xs:enumeration value="bic" />
            <xs:enumeration value="req" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="sumType"><!--5. Схема должна демонстрировать возможность описания нового сложного типа на базе как простого типа, так и сложного как путем расширения, так и путем ограничения-->
        <xs:restriction base="xs:decimal"><!--6. Схема должна демонстрировать возможности описания новых простых типов на базе существующих (в том числе описание перечислимого типа) с использованием не менее трех видов фасетов-->
            <xs:fractionDigits value="2" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="statusType"><!--5. Схема должна демонстрировать возможность описания нового сложного типа на базе как простого типа, так и сложного как путем расширения, так и путем ограничения-->
        <xs:restriction base="xs:string"><!--6. Схема должна демонстрировать возможности описания новых простых типов на базе существующих (в том числе описание перечислимого типа) с использованием не менее трех видов фасетов-->
            <xs:pattern value="[A-Z]" />
            <xs:maxLength value="1" />
        </xs:restriction>
    </xs:simpleType>

<!--    <xs:element name="users" type="tns:usersType" abstract="true" />&lt;!&ndash;4.Схема должна содержать описание абстрактного сложного типа и элемента этого типа, а пример документа - демонстрировать использование последнего&ndash;&gt;-->
<!--    <xs:complexType name="usersType" abstract="true">-->
<!--        <xs:sequence>-->
<!--            <xs:element name="username" type="xs:string" />-->
<!--        </xs:sequence>-->
<!--    </xs:complexType>-->

<!--    <xs:element name="usInfo" substitutionGroup="tns:users">-->
<!--    <xs:complexType>-->
<!--        <xs:complexContent>-->
<!--            <xs:extension base="tns:usersType"> &lt;!&ndash;5. Схема должна демонстрировать возможность описания нового сложного типа на базе как простого типа, так и сложного как путем расширения, так и путем ограничения&ndash;&gt;-->
<!--                <xs:choice>-->
<!--                    <xs:element name="usid" type="xs:string" />-->
<!--                    <xs:element name="rolid" type="xs:string" />-->
<!--                </xs:choice>-->
<!--            </xs:extension>-->
<!--        </xs:complexContent>-->
<!--    </xs:complexType>-->
<!--    </xs:element>-->

    <xs:element name="tranQueue" type="tns:tranQueueType"/>
    <xs:complexType name="tranQueueType">
        <xs:sequence>
            <xs:element name="client_list" type="tns:client_ListType" />
            <xs:element name="transactions" type="tns:transactionsType" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="client_ListType">
        <xs:sequence>
            <xs:element name="client" type="tns:clientType" maxOccurs="unbounded">
                <xs:key name="clid"><!--7. Схема должна содержать описание ограничения уникальности, ключа и ссылки на ключ, применение чего должно иметь смысл в предметной области-->
                    <xs:selector xpath="client" />
                    <xs:field xpath="@clid" />
                </xs:key>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="clientType"> <!--3.Схема должна демонстрировать использование конструкций для описания сложного типа, образованного вложенными элементами и атрибутами;-->
        <xs:sequence>
            <xs:element name="cl_dadd" type="xs:dateTime" />
            <xs:element name="cl_name" type="xs:string" />
            <xs:choice><!--3. При описании сложных типов необходимо продемонстрировать использование не менее двух видов модельных групп (sequence, choice и all)-->
                <xs:element name="client_type">
                    <xs:complexType>
                        <xs:all> <!--3. При описании сложных типов необходимо продемонстрировать использование не менее двух видов модельных групп (sequence, choice и all)-->
                            <xs:element name="cltp_name" type="xs:string" />
                            <xs:element name="cltp_desc" type="xs:string" />
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="cl_type" type="xs:string" />
            </xs:choice>
            <xs:element name="client_param"> <!--3. При этом должен быть хотя бы один сложный тип, хотя бы один вложенный элемент которого был бы также сложного типа;-->
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="param" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="p_name" type="tns:clParam" />
                                    <xs:element name="p_value" type="xs:string" />
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="client_requiset"><!--3. При этом должен быть хотя бы один сложный тип, хотя бы один вложенный элемент которого был бы также сложного типа;-->
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="req" maxOccurs="unbounded"> <!--3. При описании сложных типов необходимо продемонстрировать использование не менее двух видов модельных групп (sequence, choice и all)-->
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="req_name" type="tns:clReq" />
                                    <xs:element name="req_value" type="xs:string" />
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="document">
                <xs:complexType>
                    <xs:attribute name="image" type="xs:string" use="required" />
                </xs:complexType>
            </xs:element>
            <xs:element name="cl_status">
                <xs:complexType>
                    <xs:attribute name="param" type="xs:string" default="A" />
                </xs:complexType>
            </xs:element>
            <xs:element name="acc_list" type="tns:accListType" />
        </xs:sequence>
        <xs:attribute name="clid" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="accListType">
        <xs:sequence>
            <xs:element name="account" type="tns:accType"  maxOccurs="unbounded">
                <xs:key name="accid"><!--7. Схема должна содержать описание ограничения уникальности, ключа и ссылки на ключ, применение чего должно иметь смысл в предметной области-->
                    <xs:selector xpath="acc" />
                    <xs:field xpath="@accid" />
                </xs:key>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="accType">
        <xs:sequence>
            <xs:element name="acc_dadd" type="xs:dateTime" />
            <xs:choice><!--3. При описании сложных типов необходимо продемонстрировать использование не менее двух видов модельных групп (sequence, choice и all)-->
                <xs:element name="ac_type">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="actp_name" type="xs:string" />
                            <xs:element name="actp_desc" type="xs:string" />
                            <xs:element name="a_p" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="acc_type" type="xs:string" />
            </xs:choice>
            <xs:element name="acc_clid">
                <xs:complexType>
                    <xs:attribute name="clid" type="xs:string" />
                </xs:complexType>
                <xs:keyref name="acclid" refer="tns:clid"><!--7. Схема должна содержать описание ограничения уникальности, ключа и ссылки на ключ, применение чего должно иметь смысл в предметной области-->
                    <xs:selector xpath="acc_clid" />
                    <xs:field xpath="@clid" />
                </xs:keyref>
            </xs:element>
            <xs:element name="balance" type="tns:sumType" />
            <xs:element name="balance_free" type="tns:sumType" />
            <xs:element name="hold" type="tns:sumType" />
        </xs:sequence>
        <xs:attribute name="accid" type="xs:ID" />
    </xs:complexType>

    <xs:complexType name="transactionsType">
        <xs:sequence>
            <xs:element name="transaction" type="tns:transactionType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="transactionType">
        <xs:sequence>
            <xs:element name="tran_dadd" type="xs:dateTime"/>
            <xs:choice>
                <xs:element name="tran_type">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="trtp_name" type="xs:string"/>
                            <xs:element name="trtp_desc" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="tr_type" type="xs:string"/>
            </xs:choice>
            <xs:element name="acc_sender">
                <xs:complexType>
                    <xs:attribute name="accids" type="xs:IDREF"/>
                </xs:complexType>
                <xs:keyref name="accids" refer="tns:accid"><!--7. Схема должна содержать описание ограничения уникальности, ключа и ссылки на ключ, применение чего должно иметь смысл в предметной области-->
                    <xs:selector xpath="acc_sender"/>
                    <xs:field xpath="acсid"/>
                </xs:keyref>
            </xs:element>
            <xs:element name="acc_recip">
                <xs:complexType>
                    <xs:attribute name="accidr" type="xs:IDREF"/>
                </xs:complexType>
                <xs:keyref name="accidr" refer="tns:accid"><!--7. Схема должна содержать описание ограничения уникальности, ключа и ссылки на ключ, применение чего должно иметь смысл в предметной области-->
                    <xs:selector xpath="acc_recip"/>
                    <xs:field xpath="accid_r"/>
                </xs:keyref>
            </xs:element>
            <xs:element name="model">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="clid" type="xs:string"/>
                        <xs:element name="sum" type="tns:sumType"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="status" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="tranid" type="xs:string"/>
    </xs:complexType>
</xs:schema>

=== kalekinata/REST_service_development/bank_xml.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<tranQueue xmlns="http://namespaceTest.com/tranQueue" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="src/main/resources/XMLScheme.xsd">
    <client_list>
        <client clid="id_4D01AF61-5817-4F0A-8357-4CF902EA4234">
            <cl_dadd>2022-01-08T11:34:55.670+03:00</cl_dadd>
            <cl_name>Иванов Пётр Васильевич</cl_name>
            <client_type>
                <cltp_desc>Физическое лицо</cltp_desc>
                <cltp_name>PF</cltp_name>
            </client_type>
            <client_param>
                <param>
                    <p_name>inn</p_name>
                    <p_value>918273526178</p_value>
                </param>
            </client_param>
            <client_requiset>
                <req>
                    <req_name>bic</req_name>
                    <req_value>918273647</req_value>
                </req>
                <req>
                    <req_name>req</req_name>
                    <req_value>91827364728372635473</req_value>
                </req>
            </client_requiset>
            <document image="pasp"/>
            <cl_status param="A"/>
            <acc_list>
                <account accid="id_B9599464-A973-4926-913D-344EF3A7B330">
                    <acc_dadd>2022-01-08T11:35:56.683+03:00</acc_dadd>
                    <ac_type>
                        <actp_name>DEF</actp_name>
                        <actp_desc>Основной счёт</actp_desc>
                        <a_p>P</a_p>
                    </ac_type>
                    <acc_clid clid="id_4D01AF61-5817-4F0A-8357-4CF902EA4234"/>
                    <balance>20304.27</balance>
                    <balance_free>20304.27</balance_free>
                    <hold>0.0</hold>
                </account>
                <account accid="id_A9599464-A973-4926-913D-344EF3A7B330">
                    <acc_dadd>2022-01-20T18:47:46.683+03:00</acc_dadd>
                    <ac_type>
                        <actp_name>CRD</actp_name>
                        <actp_desc>Счёт овердрафт</actp_desc>
                        <a_p>A</a_p>
                    </ac_type>
                    <acc_clid clid="id_4D01AF61-5817-4F0A-8357-4CF902EA4234"/>
                    <balance>304.27</balance>
                    <balance_free>304.27</balance_free>
                    <hold>0.0</hold>
                </account>
            </acc_list>
        </client>
        <client clid="id_8D285579-2DB7-4D1B-94F7-7726A7FAE7E6">
            <cl_dadd>2021-12-07T11:34:55.670+03:00</cl_dadd>
            <cl_name>Цветков Василий Александрович</cl_name>
            <client_type>
                <cltp_desc>Физическое лицо</cltp_desc>
                <cltp_name>PF</cltp_name>
            </client_type>
            <client_param>
                <param>
                    <p_name>inn</p_name>
                    <p_value>918000026158</p_value>
                </param>
            </client_param>
            <client_requiset>
                <req>
                    <req_name>bic</req_name>
                    <req_value>982736425</req_value>
                </req>
            </client_requiset>
            <document image="pasp"/>
            <cl_status param="Y"/>
            <acc_list>
                <account accid="id_869B0913-CBFB-4D1D-91EE-0DF74005C792">
                    <acc_dadd>2021-12-07T11:35:46.683+03:00</acc_dadd>
                    <ac_type>
                        <actp_name>DEF</actp_name>
                        <actp_desc>Основной счёт</actp_desc>
                        <a_p>P</a_p>
                    </ac_type>
                    <acc_clid clid="id_8D285579-2DB7-4D1B-94F7-7726A7FAE7E6"/>
                    <balance>3721.25</balance>
                    <balance_free>2411.23</balance_free>
                    <hold>1310.02</hold>
                </account>
            </acc_list>
        </client>
    </client_list>
    <transactions>
        <transaction tranid="19EC8669-EFB3-4EE8-993C-CA63546702AE">
            <tran_dadd>2022-02-20T12:54:34.843+03:00</tran_dadd>
            <tran_type>
                <trtp_name>transfer</trtp_name>
                <trtp_desc>Перевод денежных средств</trtp_desc>
            </tran_type>
            <acc_sender accids="id_B9599464-A973-4926-913D-344EF3A7B330"/>
            <acc_recip accidr="id_A9599464-A973-4926-913D-344EF3A7B330"/>
            <model>
                <clid>4D01AF61-5817-4F0A-8357-4CF902EA4234</clid>
                <sum>300.92</sum>
            </model>
            <status>success</status>
        </transaction>
        <transaction tranid="997031BA-6D1E-4378-A6F0-0C57DC8D1FB9">
            <tran_dadd>2021-12-07T11:46:23+03:00</tran_dadd>
            <tran_type>
                <trtp_name>refill</trtp_name>
                <trtp_desc>Пополнение счёта</trtp_desc>
            </tran_type>
            <acc_sender accids="id_B9599464-A973-4926-913D-344EF3A7B330"/>
            <acc_recip accidr="id_A9599464-A973-4926-913D-344EF3A7B330"/>
            <model>
                <clid>4D01AF61-5817-4F0A-8357-4CF902EA4234</clid>
                <sum>300.0</sum>
            </model>
            <status>success</status>
        </transaction>
    </transactions>
</tranQueue>
